trigger:
- master

# Variables
variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build Stage

  jobs:
  - job: Build
    displayName: Build Job
    pool:
      name: default

    steps:

    # Task-1: Build & Push Docker Image
    - task: Docker@2
      inputs:
        containerRegistry: 'manual-aksdevop-svc'   # make sure this name is correct
        repository: 'custom2aksnginxapp1'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
          $(Build.SourceVersion)

    # Debug - List files
    - bash: |
        echo "Listing Source Directory"
        ls -R $(System.DefaultWorkingDirectory)

    - bash: |
        echo "Before Copy - Artifact Directory"
        ls -R $(Build.ArtifactStagingDirectory)

    # Task-2: Copy kube-manifests
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/manifests'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        OverWrite: true

    # Debug after copy
    - bash: |
        echo "After Copy - Artifact Directory"
        ls -R $(Build.ArtifactStagingDirectory)

    # Task-3: Publish Artifacts
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'kube-manifests'
        publishLocation: 'Container'

    # 🔥 BIG JAI GIREEESH BANNER
    - bash: |
        echo ""
        echo "     ██╗   █████╗   ██╗"
        echo "     ██║  ██╔══██╗  ██║"
        echo "     ██║  ███████║  ██║"
        echo "██   ██║  ██╔══██║  ██║"
        echo "╚█████╔╝  ██║  ██║  ██║"
        echo " ╚════╝   ╚═╝  ╚═╝  ╚═╝"
        echo ""
        echo " ██████╗  ██╗  ██████╗  ███████╗  ███████╗  ███████╗  ███████╗  ██╗  ██╗"
        echo "██╔════╝  ██║  ██╔══██╗ ██╔════╝  ██╔════╝  ██╔════╝  ██╔════╝  ██║  ██║"
        echo "██║  ███╗ ██║  ██████╔╝ █████╗    █████╗    █████╗    ███████╗  ███████║"
        echo "██║   ██║ ██║  ██╔══██╗ ██╔══╝    ██╔══╝    ██╔══╝    ╚════██║  ██╔══██║"
        echo "╚██████╔╝ ██║  ██║  ██║ ███████╗  ███████╗  ███████╗  ███████║  ██║  ██║"
        echo " ╚═════╝  ╚═╝  ╚═╝  ╚═╝ ╚══════╝  ╚══════╝  ╚══════╝  ╚══════╝  ╚═╝  ╚═╝"
        echo ""
        echo "================== 🚩 JAI GIREEESH 🚩 =================="
        echo ""
      displayName: '🔥 BIG JAI GIREEESH BANNER'
      condition: succeeded()